### ISSUE TITLE
Date formatting issue

### ISSUE THREAD

**Issue by ladenree** [Scion-Framework/GitHubAPI#31]
Hi, 
The php Datetime::ISO8601 does not offer a real compliant ISO8601 as described in http://php.net/manual/en/class.datetime.php#datetime.constants.iso8601

<CODE>echo (new DateTime('2012-07-08 11:14:15.638276'))->format(DateTime::ISO8601);</code>
2012-07-08T11:14:15+0200
Github expect a date like this : <code>2014-02-27T15:05:06+01:00</code>
<CODE>echo (new DateTime('2012-07-08 11:14:15.638276'))->format(DateTime::ATOM);</CODE>
2012-07-08T11:14:15+02:00

Regards,
Olivier

**Comment by emulienfou** [comment]
Thanks for this tips/bug.

Best regards,
David S.
