### ISSUE TITLE
Issues::listOrganizationIssues doesn't work

### ISSUE THREAD

**Issue by ladenree** [Scion-Framework/GitHubAPI#33]
Issues::listOrganizationIssues function have 1 bug and on my own need one enhancement.

Parameters are not passed to github API. Correct code should be 
<code>
return $this->getApi()->request(
			$this->getApi()->getString()->sprintf('/orgs/:org/issues?:args', $organization, 
				http_build_query(['filter' => $filter, 'state' => $state, 'labels' => $labels, 
					'sort' => $sort, 'direction' => $direction, 'since' => (new DateTime($since))->format(DateTime::ATOM)]))
		);</code>

The since parameter if set to '' refer to current datetime. It would be better so set it to an arbitrary old date to get all issues if blank.

Maybe in french next time ?
Olivier

**Comment by emulienfou** [comment]
Hi, salut,
Concernant le paramètre *$since*, peux-tu detailler ton idée de date dans le passée ?

Merci

**Comment by ladenree** [comment]
Si tu executes la fonction avec le suivants : $issues->listOrganizationIssues($org->login);
en laissant toutes les valeurs par défaut,  il fait l'appel suivant à l'API github
<code> https://api.github.com/orgs/myorg/issues?filter=all&state=all&labels=&sort=created&direction=desc&since=2015-12-14T09:34:59+00:00</code> ce qui ne me retourne pas d'issue.
On voit que le parametre $since est initialisé à la date d'appel de la fonction.

Pour que la fonction se comporte comme il faut avec les paramètres par défaut, il faut dans le corps de la fonction initialiser $since à une date par défaut (ex:01/01/1900).
Donc modifier la fonction comme suit: 
```php
public function listOrganizationIssues($organization, $filter = AbstractApi::FILTER_ASSIGNED, $state = AbstractApi::STATE_OPEN, $labels = '', $sort = AbstractApi::SORT_CREATED, $direction = AbstractApi::DIRECTION_DESC, $since = '') {
		if ($since=='') $since='01/01/1900';
		return $this->getApi()->request(
			$this->getApi()->getString()->sprintf('/orgs/:org/issues?:args', $organization, 
				http_build_query(['filter' => $filter, 'state' => $state, 'labels' => $labels, 
					'sort' => $sort, 'direction' => $direction, 'since' => (new DateTime($since))->format(DateTime::ATOM)]))
		);
	}
```
Et l'appel à la fonction retourne maintenant toutes les issues de l'org.
<code>https://api.github.com/orgs/gloutest/issues?filter=all&state=all&labels=&sort=created&direction=desc&since=1900-01-01T00:00:00+00:00</code>
Olivier
